[theme]
name = "solarized-dark"
[theme.overrides]
#alternating_tint_bg = "#00000000"
idle_bg = "#221133"
idle_fg = "#E4DFE8"
info_bg = "#221133"
info_fg = "#ffcc77"
separator = " "

[icons]
name = "awesome"
[icons.overrides]
cpu = " "
memory_mem = " "
net_down = ""
net_up = ""
net_vpn = "VPN"
net_wired = ""
net_wireless = ""
thermometer = " "
time = ""
update = " "

[[block]]
block = "focused_window"
max_width = 50

[[block]]
block = "net"
device = "enp2s0"
interval = 5

[[block]]
block = "music"
player = "google-play-music-desktop-player"
marquee = false
max_width = 36 #31

[[block]]
block = "pacman"

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{average}°"

[[block]]
block = "cpu"
interval = 5

# [[block]]
# block = "memory"
# display_type = "memory"
# format_mem = "{Mug}G"
# format_swap = "{SUg}G"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 1
format = "%a %m-%d %R:%S"

# [[block]]
# block = "backlight"

# [[block]]
# block = "battery"
# device = "BAT1"
# show = "both"

# TODO

# Cross-platform (Y570, PC-Mordor branches?)
# Remove redundant icons

# Ping

# PC-Mordor only?
# Nvidia GPU

# Y570 only:
# No 2018
# Backlight
# Battery
